/**
 * Common constants for all features.
 */
export class CommonConstants {
  /** 主色 */
  static readonly COLOR_MAIN = '#006d77';
  static readonly COLOR_TEXT_MAIN = '#fff';
  static readonly COLOR_TEXT_IN = '#386641';
  static readonly COLOR_TEXT_OUT = '#ef233c';
  /** 次要色 */
  static readonly COLOR_SECONDARY = '#83c5be';
  /** 其他色1 */
  static readonly COLOR_OTHER1 = '#edf6f9';
  /** 其他色2 */
  static readonly COLOR_OTHER2 = '#ffddd2';
  /** 其他色3 */
  static readonly COLOR_OTHER3 = '#e29578';
  /** 盒子阴影 */
  static readonly BOX_SHADOW: ShadowOptions = { radius: 10, color: Color.Gray };
}